In [1]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [2]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [3]:
scaler = StandardScaler()

In [4]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [5]:
scaler.mean_

array([0.5, 0.5])

In [6]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [7]:
scaler.transform([[2, 2]])

array([[3., 3.]])

In [10]:
class MyStandardScaler:
    def __init__(self):
        self.data_mean_ = None
        self.data_std_ = None
    
    def fit(self, data):
        self.data_mean_ = np.mean(data, axis = 0)
        self.data_std_ = np.std(data, axis = 0)
        
    def transform(self, data):
        new_data = (np.array(data)-self.data_mean_)/(self.data_std_)
        return new_data
    
    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)

In [18]:
np.mean(data, axis =1)

array([0., 0., 1., 1.])

In [9]:
np.std(data, axis = 0)

array([0.5, 0.5])

In [11]:
mystandard = MyStandardScaler()

In [12]:
mystandard.fit(data)

In [13]:
mystandard.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [14]:
mystandard2 = MyStandardScaler()

In [16]:
mystandard2.fit_transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])